# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZzuna4Bm2UWFiJ66JoU1ZFqAghZjoI3
"""

import streamlit as st
import pandas as pd
import joblib
import os
import datetime
import xgboost as xgb
import requests
import json
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import threading
import time
from PIL import Image
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder



# setting the current working directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
os.chdir(SCRIPT_DIR)


# --- 1. Brief Introduction ---
def page_introduction():
    """Sets up the introduction section of the app."""
    st.title("🛡️ Insurance Fraud Detection Simulator")
    st.subheader("Leveraging Logistic Regression for Proactive Claims Review")

    st.markdown("""
        Our goal is to **identify potential fraud cases** quickly and accurately so that our real-life agents can focus their time on cases that truly require human investigation.

        ---

        ### The System Flow (Model Working Behind the Scenes)
        In a live environment, the process is automatic:
        1.  **Customer Files Claim:** New insurance and claim data are recorded instantly.
        2.  **Model Prediction:** Our **Logistic Regression Model** runs on the backend, calculating a fraud probability score.
        3.  **Agent Review:** High-risk claims are immediately flagged for human agents to check.

        This website simulates Step 2 and 3, allowing you to **input data** and see the model's fraud prediction in real-time.
    """)

# --- 2. Model Showcase & Data Input ---
def page_model_showcase():
    """Sets up the input form for model simulation."""
    st.title("🔍 Model Simulation: Enter Claim Details")
    st.subheader("Input your policy and incident information below:")

    # Placeholder for the prediction result (to be shown later)
    prediction_placeholder = st.empty()

    with st.form("claim_input_form"):
        # --- Policyholder and Policy Details ---
        st.header("1. Policy & Customer Details")
        col1, col2, col3 = st.columns(3)

        with col1:
            st.number_input("Months as Customer", min_value=0, max_value=600, value=100, step=1, key="months_as_customer", help="Number of months the individual has been a customer.")
            st.number_input("Age", min_value=18, max_value=100, value=40, step=1, key="age", help="Age of the insured individual.")
            st.selectbox("Policy State", options=['OH', 'IN', 'IL'], key="policy_state")

        with col2:
            st.selectbox("Insured Sex", options=['Male', 'Female'], key="insured_sex")
            st.selectbox("Education Level", options=['JD', 'High School', 'Associate', 'MD', 'Masters', 'PhD', 'College'], key="insured_education_level")
            st.selectbox("Relationship", options=['Husband', 'Wife', 'Own-child', 'Unmarried', 'Other-relative', 'Not-in-family'], key="insured_relationship")

        with col3:
            st.selectbox("CSL", options=['100/300', '250/500', '500/1000'], key="policy_csl")
            st.number_input("Deductible", min_value=500, max_value=2000, value=1000, step=100, key="policy_deductable")
            st.number_input("Annual Premium", value=1200.00, format="%.2f", key="policy_annual_premium")

        st.markdown("---")

        # --- Incident and Claim Details ---
        st.header("2. Incident & Claim Information")
        col4, col5, col6 = st.columns(3)

        with col4:
            st.selectbox("Incident Type", options=['Single Vehicle Collision', 'Multi-vehicle Collision', 'Vehicle Theft', 'Parked Car'], key="incident_type")
            st.selectbox("Collision Type", options=['Rear Collision', 'Side Collision', 'Front Collision', 'Missing'], key="collision_type")
            st.selectbox("Severity", options=['Minor Damage', 'Major Damage', 'Total Loss', 'Trivial Damage'], key="incident_severity")

        with col5:
            st.selectbox("Authorities Contacted", options=['Police', 'Fire', 'Ambulance', 'None', 'Other'], key="authorities_contacted")
            st.number_input("Hour of Incident (0-23)", min_value=0, max_value=23, value=14, step=1, key="incident_hour_of_the_day")
            st.number_input("Vehicles Involved", min_value=1, max_value=15, value=2, step=1, key="number_of_vehicles_involved")

        with col6:
            st.number_input("Total Claim Amount", min_value=0, value=50000, step=1000, key="total_claim_amount")
            st.number_input("Injury Claim", min_value=0, value=5000, step=500, key="injury_claim")
            st.number_input("Vehicle Claim", min_value=0, value=40000, step=1000, key="vehicle_claim")

        # Binary/Simple Inputs
        st.markdown("---")
        st.subheader("3. Supplementary Details")
        col7, col8, col9 = st.columns(3)

        with col7:
            # Note: This is simplified, as Hobbies has many unique values.
            st.selectbox("Insured Occupation", options=['tech', 'craftsman', 'sales', 'clerical', 'protective-service', 'transportation'], key="insured_occupation")
            st.number_input("Witnesses", min_value=0, max_value=10, value=0, key="witnesses")
            st.selectbox("Property Damage?", options = ['Yes', 'No', 'Missing'], key="property_damage")

        with col8:
            # Auto details simplified for demonstration
            st.selectbox("Auto Make", options=['Honda', 'Toyota', 'BMW', 'Subaru', 'Ford'], key="auto_make")
            st.number_input("Capital Gains", value=0, step=100, key="capital-gains")
            st.number_input("Bodily Injuries?", value = 0, min_value = 0, max_value = 2, step = 1, key="bodily_injuries")

        with col9:
            st.number_input("Auto Year", min_value=1990, max_value=2025, value=2015, step=1, key="auto_year")
            st.number_input("Capital Loss", value=0, step=100, key="capital-loss")
            st.selectbox("Police Report Available?", options = ['Yes', 'No', 'Missing'],key="police_report_available")


        # --- Submission Button ---
        st.markdown("---")
        submitted = st.form_submit_button("Submit Claim for Fraud Prediction")

    # --- Prediction Logic (Runs after Submission) ---
    if submitted:
        # NOTE: You will need to replace this placeholder logic with your actual model loading and prediction code.
        # This function currently returns a dummy probability.
        fraud_probability = generate_dummy_prediction(st.session_state)

        # Update the placeholder with the prediction result
        with prediction_placeholder.container():
            st.subheader("⚡ Model Prediction Result")
            if fraud_probability >= 0.5:
                st.error(f"**FRAUD LIKELY!** 🚨 The model predicts a {fraud_probability*100:.2f}% chance of fraud.")
                st.info("Recommendation: Flag this claim for immediate human agent review.")
            else:
                st.success(f"**LOW RISK.** ✅ The model predicts a {fraud_probability*100:.2f}% chance of fraud.")
                st.info("Recommendation: Proceed with standard automated claim processing.")

# --- Dummy Prediction Function (Replace with your actual model logic) ---
def generate_dummy_prediction(input_data):
    """
    A placeholder function to simulate a prediction.
    REPLACE this with your actual model loading and prediction pipeline.
    """
    # Example: A high deductible and major damage might increase the dummy fraud risk
    risk_score = 0
    if input_data.get('policy_deductable') >= 1500:
        risk_score += 0.2
    if input_data.get('incident_severity') == 'Total Loss':
        risk_score += 0.3
    
    # Use a random component to simulate model complexity
    random_factor = np.random.uniform(-0.1, 0.2)
    final_prob = np.clip(0.1 + risk_score + random_factor, 0.01, 0.99)
    return final_prob

# --- Main App Execution ---
if __name__ == "__main__":
    # You can use pages here, but for simplicity, we'll put the introduction first
    page_introduction()
    st.markdown("---")
    page_model_showcase()